### ISSUE TITLE
hmm

### ISSUE THREAD

**Issue by helix4u** [TheSmellOfVictory/poe_sniper#1]
get this after about 5 min 
http://i.imgur.com/bvpGhlu.png

**Comment by TheSmellOfVictory** [comment]
I have now fixed all of the memory leaks in the script.

**Comment by helix4u** [comment]
Sweet, I'll give it a whirl.
Other thing I did was change teh message to match poe.trade like so
`            found_item = ujson.loads(found_item)
            print(
                found_item['price'], "\t"
                "@" + character_name,
                "Hi, I would like to buy your", found_item['name'],
                "listed for", found_item['price'],
                "in", found_item['league'],
                "(stash tab:",
                '"'+ tab + '"' + ";",
                "position: left",
                found_item['x'] + ",",
                "top",
                found_item['y'] + ")")
            print('\a', end="")`

**Comment by helix4u** [comment]
or i guess like this now http://i.imgur.com/fiMS6Tj.png

**Comment by TheSmellOfVictory** [comment]
Cool, I changed my code to match that format too.
